### ISSUE TITLE
Update logging level to 'error'?

### ISSUE THREAD

**Issue by gchan** [buildkite/test-collector-ruby#141]
https://github.com/buildkite/test-collector-ruby/blob/1118897f153bd248d741d175b0b9b759b69a0d2f/lib/buildkite/test_collector/socket_connection.rb#L81

Should the logging level be `error` to be consistent with the subsequent lines?

https://github.com/buildkite/test-collector-ruby/blob/1118897f153bd248d741d175b0b9b759b69a0d2f/lib/buildkite/test_collector/socket_connection.rb#L88-L103

**Comment by JuanitoFatas** [comment]
Yup, good catch! Do you want to make a Pull Request?
