### ISSUE TITLE
Network connectivity during final report causing test process to exit with non-zero status

### ISSUE THREAD

**Issue by jebentier** [buildkite/test-collector-ruby#161]
Just recently got the free trial set up and using Test Analytics so we can see what our expected usage and value will be for the service. Something we've noticed is that when there are connectivity issues with Buildkite's servers (whether they be connections being disconnected, or DNS resolution breaking) they do not cause tests to fail, but the final report at the end of the test run will fail and cause the process to exit with a non-zero exit status.

This is causing pain in our CI system that's currently running with Test Analytics enabled.

I was able to recreate this when running a test locally by shutting off my WiFi half way through the tests. Minitest will report no test failures (because there aren't any) but exit status will be (1) due to an `Errno::ETIMEDOUT` error being raised out of `socket_connection`.

```
$> CI=true BUILDKITE_ANALYTICS_TOKEN=<redacted> bundle exec rake automated_test:run TEST_FILES="path/to/test/file_test.rb"
** Invoke automated_test:run (first_time)
** Execute automated_test:run
Run options: --seed 29935

# Running:

....

Finished in 60.421516s, 0.0662 runs/s, 0.1324 assertions/s.

4 runs, 8 assertions, 0 failures, 0 errors, 0 skips
#<Thread:0x00007fc585702c70 /Users/jebentier/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/buildkite-test_collector-1.2.5/lib/buildkite/test_collector/socket_connection.rb:64 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        2: from /Users/jebentier/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/buildkite-test_collector-1.2.5/lib/buildkite/test_collector/socket_connection.rb:69:in `block in initialize'
        1: from /Users/jebentier/.rbenv/versions/2.7.5/lib/ruby/2.7.0/openssl/buffering.rb:125:in `readpartial'
/Users/jebentier/.rbenv/versions/2.7.5/lib/ruby/2.7.0/openssl/buffering.rb:125:in `sysread': Operation timed out (Errno::ETIMEDOUT)
Traceback (most recent call last):
        2: from /Users/jebentier/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/buildkite-test_collector-1.2.5/lib/buildkite/test_collector/socket_connection.rb:69:in `block in initialize'
        1: from /Users/jebentier/.rbenv/versions/2.7.5/lib/ruby/2.7.0/openssl/buffering.rb:125:in `readpartial'
/Users/jebentier/.rbenv/versions/2.7.5/lib/ruby/2.7.0/openssl/buffering.rb:125:in `sysread': Operation timed out (Errno::ETIMEDOUT)
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/Users/jebentier/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-12.3.3/lib" "/Users/jebentier/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-12.3.3/lib/rake/rake_test_loader.rb" "test/lib/deploy/health_checks/call_event_worker_test.rb" ]
/Users/jebentier/.rbenv/versions/2.7.5/bin/bundle:23:in `load'
/Users/jebentier/.rbenv/versions/2.7.5/bin/bundle:23:in `<main>'
Tasks: TOP => automated_test:run
(See full trace by running task with --trace)
```

I noticed that in https://github.com/buildkite/test-collector-ruby/pull/145 a fix was put in to make sure errors raised while failing to connect to Buildkite's server doesn't cause tests to fail. Would it be possible to get a similar protection around the final report at the end of the test run, so that network connectivity issues don't negatively affect test runs?

**Comment by blaknite** [comment]
Thanks for reporting this @jebentier. We're very keen to ensure the ruby collector fails gracefully and doesn't break builds!

I think we have some disconnection exceptions being caught for `socket_connection` but it would seem this one's been missed. I've scheduled a fix with the Test Analytics team. We'll let you know when the fix is ready 😊

**Comment by blaknite** [comment]
@jebentier the fix is now in main. If you like, you can test it out by installing the gem from git. If not, we'll be releasing a new version of the gem in the next couple of days.

**Comment by jebentier** [comment]
Sorry for the delay on this. I was able to test this out and this issue is resolved. Thank you and your team for the quick turnaround on this. Appreciate it.
