### ISSUE TITLE
Gem isn't ruby 2.3 compatible

### ISSUE THREAD

**Issue by alagos** [buildkite/test-collector-ruby#199]
That's what is defined [in the gemspec](https://github.com/buildkite/test-collector-ruby/blob/main/buildkite-test_collector.gemspec#L25), but it has ruby 2.6 syntax [like this](https://github.com/buildkite/test-collector-ruby/blob/main/lib/buildkite/test_collector/minitest_plugin/trace.rb#L77) which makes the gem to fail in older versions (ruby 2.4 in my case), so it should be updated the gemspec or change that syntax to make it compatible with older ruby versions.

**Comment by gchan** [comment]
Hi @alagos , it sounds like your preference is for Ruby 2.4 to remain supported (let me know otherwise!).

I'll check with the team to see whether [EOL Ruby versions](https://www.ruby-lang.org/en/downloads/branches/) should continue to be supported.

**Comment by alagos** [comment]
Well, if ruby 2.4 can be supported, that would be awesome. We're still in the process to upgrade to supported ruby versions, but in the meantime would be nice to have access to this gem.

**Comment by gchan** [comment]
Hi @alagos , I'm working on restoring comparability for Ruby 2.3 over at #201 , let me know if you have any feedback or comments!

Support for Ruby 2.4 will not be permanent and we will likely have a plan to gradually drop support for older versions of Ruby. 

How long do you think your team requires Ruby 2.4 support?

**Comment by alagos** [comment]
@gchan wow, that's great. 
We're in the process to upgrade our stack (a year ago we were with ruby 2.2), so hopefully a year from now.

**Comment by gchan** [comment]
Hi @alagos , we've published a new version of the gem which supports Ruby versions 2.3 and above.

https://github.com/buildkite/test-collector-ruby/releases/tag/v2.3.2

Please note support for EOL'ed versions of Ruby may be removed in the future.

**Comment by alagos** [comment]
Sure, I'll keep in mind.
Thanks for all
